<#
.SYNOPSIS
  Install fleet live-console scripts onto qodesh (or shalom).

.DESCRIPTION
  Creates console data dirs, copies pack scripts, optional Start Menu / Desktop shortcut.
  Does NOT clone repos, download packages, or touch credentials.

.PARAMETER PackSource
  Directory containing this pack (start-watch-windows.ps1, etc.).
  Default: directory of this script.

.PARAMETER TargetRoot
  Where scripts land. Default: C:\fleet\console\pack

.PARAMETER DataRoot
  Where logs live. Default: C:\fleet\console

.PARAMETER AlsoDocuments
  Also ensure Documents\green-roomz\data\_console exists (secondary path).

.PARAMETER Shortcut
  Create a Desktop shortcut "Fleet Live Console".
#>
[CmdletBinding()]
param(
  [string]$PackSource = '',
  [string]$TargetRoot = 'C:\fleet\console\pack',
  [string]$DataRoot = 'C:\fleet\console',
  [switch]$AlsoDocuments,
  [switch]$Shortcut
)

$ErrorActionPreference = 'Stop'

if (-not $PackSource) {
  if ($PSScriptRoot) { $PackSource = $PSScriptRoot }
  else { $PackSource = Split-Path -Parent $MyInvocation.MyCommand.Path }
}

if (-not (Test-Path -LiteralPath $PackSource)) {
  throw "PackSource not found: $PackSource"
}

Write-Host "PackSource : $PackSource"
Write-Host "TargetRoot : $TargetRoot"
Write-Host "DataRoot   : $DataRoot"

New-Item -ItemType Directory -Force -Path $TargetRoot | Out-Null
New-Item -ItemType Directory -Force -Path $DataRoot | Out-Null

foreach ($name in @('console.log', 'prompt.log', 'response.log')) {
  $p = Join-Path $DataRoot $name
  if (-not (Test-Path -LiteralPath $p)) {
    New-Item -ItemType File -Force -Path $p | Out-Null
  }
}

if ($AlsoDocuments) {
  $doc = Join-Path $env:USERPROFILE 'Documents\green-roomz\data\_console'
  New-Item -ItemType Directory -Force -Path $doc | Out-Null
  foreach ($name in @('console.log', 'prompt.log', 'response.log')) {
    $p = Join-Path $doc $name
    if (-not (Test-Path -LiteralPath $p)) {
      New-Item -ItemType File -Force -Path $p | Out-Null
    }
  }
  Write-Host "AlsoDocuments: $doc"
}

$files = @(
  'start-watch-windows.ps1',
  'install-qodesh.ps1',
  'README.md',
  'start-watch-box.sh'
)
$copied = @()
foreach ($f in $files) {
  $src = Join-Path $PackSource $f
  if (Test-Path -LiteralPath $src) {
    Copy-Item -LiteralPath $src -Destination (Join-Path $TargetRoot $f) -Force
    $copied += $f
  } else {
    Write-Warning "Missing in pack (skipped): $f"
  }
}

# Tiny launcher wrapper that pins ConsoleRoot
$launcher = Join-Path $TargetRoot 'Start-FleetConsole.ps1'
@"
# Auto-generated by install-qodesh.ps1 — host-local live console
`$ErrorActionPreference = 'Stop'
& (Join-Path `$PSScriptRoot 'start-watch-windows.ps1') -ConsoleRoot '$DataRoot' @args
"@ | Set-Content -LiteralPath $launcher -Encoding UTF8
$copied += 'Start-FleetConsole.ps1'

Write-Host "Copied: $($copied -join ', ')"

if ($Shortcut) {
  $desktop = [Environment]::GetFolderPath('Desktop')
  $lnkPath = Join-Path $desktop 'Fleet Live Console.lnk'
  $shell = New-Object -ComObject WScript.Shell
  $lnk = $shell.CreateShortcut($lnkPath)
  $lnk.TargetPath = 'powershell.exe'
  $lnk.Arguments = "-NoProfile -ExecutionPolicy Bypass -File `"$launcher`""
  $lnk.WorkingDirectory = $TargetRoot
  $lnk.WindowStyle = 1
  $lnk.Description = 'Fleet live worker/stats console (host-local)'
  $lnk.Save()
  Write-Host "Shortcut: $lnkPath"
}

Write-Host ''
Write-Host 'Install complete. Start with:'
Write-Host "  powershell -NoProfile -ExecutionPolicy Bypass -File `"$launcher`""
Write-Host 'Or open Task Manager on this host for CPU/RAM (do not scrape into Linux console).'
